server:
  port: ${ENV_SERVER_PORT:9090}
  servlet:
    context-path: ${ENV_CONTEXT_PATH:/society/api}

  error:
    whitelabel:
      enabled: false
    path: /error-413

logging:
  print:
    payload: ${ENV_PRINT_PAYLOAD:true}
  level:
    root: ${ENV_ROOT_LOG_LEVEL:INFO}
    com.one: ${ENV_ONE_LOG_LEVEL:DEBUG}

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    show-sql: true # Enables SQL query logging
    properties:
      hibernate:
        jdbc.batch_size: 30
    hibernate:
      naming:
        physical-strategy: com.one.societyAPI.config.CustomCaseNamingStrategy
      ddl-auto: update # Use 'create' for first-time setup, 'update' for changes
  jackson:
    serialization:
      write-dates-as-timestamps: false
  profiles:
    active: ${ENV_PROFILE:local}
  output: 
    ansi: 
      enabled: always
  application:
    name: ${ENV_APP_NAME:society_api}
  datasource:

    #url: jdbc:mysql://13.233.142.6:3306/society
    #username: m00nSocietry
    #password: m00nSocietry

    url: jdbc:mysql://localhost:3306/society
    username: root
    password: root

    #url: ${ENV_DB_URL:jdbc:mysql://13.203.86.197:3306/society}
    #username: ${ENV_DB_USERNAME:society}
    #password: ${ENV_DB_PASSWORD:password}
    #driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
          ddl-auto: update  # Change as needed: none, validate, create, or create-drop
        show-sql: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: Motionsorange@gmail.com
    password: hxmg oqmz aegg txlr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
cors:
  allowed-origins: "http://localhost:3000"


springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

jwt:
  secret: "c2VjdXJlLXNlY3JldC1rZXktZm9yLWp3dC1hdXRoZW50aWNhdGlvbg=="  # Replace with a strong secret key
  expirationMs: 3600000       # Token expiration time in milliseconds (e.g., 1 hour)

management:
  endpoints:
    web:
      exposure:
        include: "*" 


feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 5000